behaviors:
    car_training_config:
        trainer_type: ppo
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 4
            shared_critic: false
            learning_rate_schedule: linear
            beta_schedule: linear
            epsilon_schedule: linear
        checkpoint_interval: 500000
        network_settings:
            normalize: true
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
            memory: null
            goal_conditioning_type: hyper
            deterministic: false
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
                network_settings:
                    normalize: false
                    hidden_units: 256
                    num_layers: 2
                    vis_encode_type: simple
                    memory: null
                    goal_conditioning_type: hyper
                    deterministic: false
        init_path: null
        keep_checkpoints: 5
        even_checkpoints: false
        max_steps: 5000000
        time_horizon: 256
        summary_freq: 10000
        threaded: true
        self_play: null
        behavioral_cloning: null