behaviors:
  car_training_config: 
    trainer_type: ppo
    hyperparameters:
      batch_size: 128          # Increased from 64 for more stable learning
      buffer_size: 4096        # Increased to allow for larger batch size
      learning_rate: 1.0e-4    # Slightly lower for more stable learning
      beta: 1.0e-3            # Increased for better exploration
      epsilon: 0.2            # Good default for PPO
      lambd: 0.95             # Good default for PPO
      num_epoch: 4            # Increased slightly for better policy refinement
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256       # Increased for more complex behavior
      num_layers: 3          # Added an extra layer for more capacity
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99          # Good for continuous task
        strength: 1.0
      curiosity:             # Added intrinsic motivation
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
    max_steps: 2000000       # Increased for better learning
    time_horizon: 128        # Increased to capture longer sequences
    summary_freq: 10000
    checkpoint_interval: 50000
    threaded: true           # Enable threaded operation
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5